# Generated by Django 5.0.6 on 2024-06-29 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=1024)),
                ('category', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(choices=[('BRL', 'BRL')], max_length=3)),
                ('stock_quantity', models.PositiveBigIntegerField()),
                ('stock_record_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
